import './style.css';

type Caption = { text: string; at: Date };
let stream: MediaStream | undefined;
let processor: ScriptProcessorNode | undefined;
let audioContext: AudioContext | undefined;
let samples: number[] = [];
let captions: Caption[] = [];
let running = false;
let transcribing = false;

const $ = <T extends Element>(selector: string) => document.querySelector<T>(selector)!;
const app = $('#main');

app.innerHTML = `
  <div class="shell">
    <header class="masthead"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"></span>Private Call Captions</a><a class="privacy-link" href="/privacy/">Privacy</a></header>
    <section class="intro" aria-labelledby="page-title"><div><p class="eyebrow">Microphone-only companion</p><h1 id="page-title">Keep the words close.</h1><p class="lede">Readable captions for your private call, processed by a model you keep on this computer. No system audio. No recording. No cloud transcript.</p><div class="privacy-promise"><span class="lock" aria-hidden="true">▣</span><div><strong>Your boundary is explicit</strong><p>Only the microphone you select is used. Audio buffers are discarded after local transcription.</p></div></div></div>
      <section class="caption-sheet" aria-label="Live caption preview"><header><span>Caption layer</span><span class="local-chip">● local only</span></header><output class="caption-output empty" id="caption" aria-live="polite">Choose a microphone and local model to start.</output></section></section>
    <section class="controls" aria-label="Caption controls"><section class="panel"><h2>Start a private caption session</h2><p class="hint">Bring your own Whisper-compatible <abbr title="Graphics General Matrix Multiplication">GGML</abbr> model file. The model never leaves this device.</p><div class="fields"><label for="microphone">Microphone<select id="microphone"><option value="">Choose a microphone…</option></select></label><label for="model">Local model path<input id="model" autocomplete="off" placeholder="Choose a .bin / .gguf model file" /></label></div><div class="action-row"><button class="button" id="choose-model" type="button">Choose model</button><button class="button primary" id="start" type="button">Start captions</button><button class="button warn" id="stop" type="button" disabled>Stop</button><button class="button" id="overlay" type="button">Open caption window</button></div><p class="status" id="status" role="status" aria-live="polite"></p></section>
      <aside class="consent"><h2>Before you begin</h2><p>Tell people captions are running when that is expected or required. This is an accessibility aid, not legal transcription or an emergency service. Noise, names, and accents can be misheard.</p><label style="margin-top:14px;display:flex;gap:10px;align-items:flex-start;font-weight:600"><input id="consent" type="checkbox" style="width:22px;min-height:22px;margin-top:1px"/>I understand the limits and will follow my call’s consent rules.</label></aside></section>
    <section class="panel" aria-labelledby="transcript-title"><div class="transcript-tools"><div><h2 id="transcript-title">Session text</h2><p class="hint">Kept in memory until you export or close the app.</p></div><div class="action-row"><button class="button" id="correct" type="button" disabled>Correct last <kbd>⌘/Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd></button><button class="button" id="export-txt" type="button" disabled>Export TXT</button><button class="button" id="export-csv" type="button" disabled>Export CSV</button><button class="button" id="clear" type="button" disabled>Clear session</button></div></div><div class="transcript" id="transcript"><p class="muted">Your local captions will collect here. Nothing is saved automatically.</p></div></section>
    <footer class="footer"><span>Generated illustration is original AI-assisted artwork · no telemetry</span><nav aria-label="Legal"><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="https://api.sociobot.in/api/v1/products/private-call-captions/checkout">One-time unlock</a></nav></footer>
  </div>`;

const mic = $('#microphone') as HTMLSelectElement;
const model = $('#model') as HTMLInputElement;
const consent = $('#consent') as HTMLInputElement;
const caption = $('#caption') as HTMLOutputElement;
const status = $('#status') as HTMLElement;
const start = $('#start') as HTMLButtonElement;
const stop = $('#stop') as HTMLButtonElement;

function setStatus(message: string, kind: 'error' | 'success' | '' = '') { status.textContent = message; status.dataset.kind = kind; }
function formatTime(at: Date) { return at.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }); }
function renderTranscript() { const transcript = $('#transcript'); transcript.innerHTML = captions.length ? captions.map((item, i) => `<p data-index="${i}"><span class="timestamp">${formatTime(item.at)}</span>${escapeHtml(item.text)}</p>`).join('') : '<p class="muted">Your local captions will collect here. Nothing is saved automatically.</p>'; for (const el of document.querySelectorAll<HTMLButtonElement>('#correct,#export-txt,#export-csv,#clear')) el.disabled = !captions.length; }
function escapeHtml(value: string) { const node = document.createElement('span'); node.textContent = value; return node.innerHTML; }
function downsample(input: Float32Array, sourceRate: number) { const ratio = sourceRate / 16000; const length = Math.floor(input.length / ratio); const output = new Array<number>(length); for (let i = 0; i < length; i++) { const startAt = Math.floor(i * ratio); const endAt = Math.min(Math.floor((i + 1) * ratio), input.length); let sum = 0; for (let j = startAt; j < endAt; j++) sum += input[j]; output[i] = sum / Math.max(1, endAt - startAt); } return output; }
async function native<T>(command: string, args?: Record<string, unknown>): Promise<T> { const { invoke } = await import('@tauri-apps/api/core'); return invoke<T>(command, args); }
async function refreshDevices() { try { const temp = await navigator.mediaDevices.getUserMedia({ audio: true }); temp.getTracks().forEach(t => t.stop()); const devices = await navigator.mediaDevices.enumerateDevices(); mic.innerHTML = '<option value="">Choose a microphone…</option>' + devices.filter(d => d.kind === 'audioinput').map(d => `<option value="${d.deviceId}">${escapeHtml(d.label || 'Microphone')}</option>`).join(''); setStatus('Microphones are ready. Selecting one never captures system audio.', 'success'); } catch { setStatus('Microphone permission was not granted. Allow microphone access, then reload this app.', 'error'); } }
async function deliverChunk() { if (!running || transcribing || samples.length < 64000) return; const chunk = samples.splice(0, 64000); transcribing = true; try { const text = await native<string>('transcribe_chunk', { modelPath: model.value, samples: chunk }); if (text.trim()) addCaption(text.trim()); } catch (error) { setStatus(`Could not transcribe locally: ${String(error)}. Check the Whisper model file and try again.`, 'error'); stopSession(); } finally { transcribing = false; } }
async function addCaption(text: string) { const item = { text, at: new Date() }; captions.push(item); caption.textContent = text; caption.classList.remove('empty'); renderTranscript(); try { const { emit } = await import('@tauri-apps/api/event'); await emit('caption', { text, at: item.at.toISOString() }); } catch { /* browser preview has no native overlay */ } }
async function startSession() { if (!consent.checked) return setStatus('Confirm the consent guidance before starting captions.', 'error'); if (!mic.value) return setStatus('Choose a microphone first.', 'error'); if (!model.value.trim()) return setStatus('Choose a local Whisper-compatible model file first.', 'error'); try { stream = await navigator.mediaDevices.getUserMedia({ audio: { deviceId: { exact: mic.value }, echoCancellation: true, noiseSuppression: true, autoGainControl: true }, video: false }); audioContext = new AudioContext(); const source = audioContext.createMediaStreamSource(stream); processor = audioContext.createScriptProcessor(4096, 1, 1); processor.onaudioprocess = event => { event.outputBuffer.getChannelData(0).fill(0); if (!running) return; samples.push(...downsample(event.inputBuffer.getChannelData(0), audioContext!.sampleRate)); void deliverChunk(); }; source.connect(processor); processor.connect(audioContext.destination); running = true; start.disabled = true; stop.disabled = false; caption.textContent = 'Listening locally…'; caption.classList.remove('empty'); setStatus('Captioning from the selected microphone. Audio is processed locally and immediately discarded.', 'success'); } catch (error) { setStatus(`Could not open that microphone: ${String(error)}`, 'error'); } }
function stopSession() { running = false; processor?.disconnect(); processor = undefined; stream?.getTracks().forEach(track => track.stop()); stream = undefined; void audioContext?.close(); audioContext = undefined; samples = []; start.disabled = false; stop.disabled = true; setStatus('Caption session stopped. Nothing was retained except the session text shown below.', 'success'); }
function exportFile(kind: 'txt' | 'csv') { const content = kind === 'txt' ? captions.map(c => `[${formatTime(c.at)}] ${c.text}`).join('\n') : ['timestamp,caption', ...captions.map(c => `"${c.at.toISOString()}","${c.text.replaceAll('"', '""')}"`)].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([content], { type: kind === 'txt' ? 'text/plain' : 'text/csv' })); a.download = `private-call-captions-${new Date().toISOString().slice(0, 10)}.${kind}`; a.click(); URL.revokeObjectURL(a.href); setStatus(`Exported local ${kind.toUpperCase()} file.`, 'success'); }
$('#choose-model').addEventListener('click', async () => { try { const { open } = await import('@tauri-apps/plugin-dialog'); const picked = await open({ multiple: false, filters: [{ name: 'Whisper models', extensions: ['bin', 'gguf'] }] }); if (typeof picked === 'string') { model.value = picked; localStorage.setItem('pcc:model', picked); } } catch { setStatus('Model picker is available in the desktop app. Paste a local model path in this browser preview.', 'error'); } });
start.addEventListener('click', startSession); stop.addEventListener('click', stopSession); $('#overlay').addEventListener('click', async () => { try { await native('open_caption_window'); setStatus('Opened a resizable caption window.', 'success'); } catch { setStatus('The separate caption window is available in the installed desktop app.', 'error'); } });
$('#correct').addEventListener('click', () => { const last = captions.at(-1); if (!last) return; const corrected = window.prompt('Correct the last caption:', last.text); if (corrected?.trim()) { last.text = corrected.trim(); caption.textContent = last.text; renderTranscript(); setStatus('Last caption corrected locally.', 'success'); } });
$('#export-txt').addEventListener('click', () => exportFile('txt')); $('#export-csv').addEventListener('click', () => exportFile('csv')); $('#clear').addEventListener('click', () => { if (window.confirm(`Clear ${captions.length} caption${captions.length === 1 ? '' : 's'} from this session? This cannot be undone.`)) { captions = []; caption.textContent = 'Session cleared. Start captions when ready.'; caption.classList.add('empty'); renderTranscript(); setStatus('Session text cleared.', 'success'); } });
window.addEventListener('keydown', event => { if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key.toLowerCase() === 'e') { event.preventDefault(); ($('#correct') as HTMLButtonElement).click(); } });
model.value = localStorage.getItem('pcc:model') ?? ''; void refreshDevices();
